"""
backend/core/hyde.py

WHAT THIS DOES:
  Implements HyDE (Hypothetical Document Embeddings), a retrieval
  technique from the paper "Precise Zero-Shot Dense Retrieval without
  Relevance Labels" (Gao et al., 2022).

HOW HyDE WORKS (interview explanation):
  The problem: Questions and answers live in different embedding spaces.
  "What is the boiling point of water?" (question-shaped)
  "Water boils at 100°C at sea level." (answer-shaped)
  These two sentences are not as close in embedding space as you'd hope.
  Documents in your corpus are answer-shaped (they state facts).
  Queries are question-shaped. This mismatch hurts retrieval.

  HyDE solution:
    1. Give the query to the LLM
    2. Ask it to write a SHORT hypothetical answer (even if it hallucinates)
    3. Embed that hypothetical answer instead of the raw query
    4. The hypothetical answer embedding is answer-shaped
       → much closer to real document chunks in embedding space
    5. Use that vector for dense (FAISS) retrieval

  IMPORTANT: HyDE only affects DENSE retrieval.
  BM25 still gets the original raw query — it needs real words.
  This is handled in HybridSearcher.search_by_vector() (Step 5).

  WHY HALLUCINATIONS ARE OK HERE:
  The hypothetical answer doesn't need to be factually correct.
  We're only using its EMBEDDING as a search vector, not its content.
  A hallucinated answer about the right topic still produces a
  better search vector than the raw question.

WHAT THIS MODULE EXPORTS:
  HyDEExpander — generates hypothetical answer + its embedding
  get_hyde_expander() — module-level singleton factory
"""

from typing import Tuple, Optional
import numpy as np

from langchain_groq import ChatGroq
from langchain.schema import HumanMessage, SystemMessage

from core.config import get_settings
from core.embeddings import embed_query


# ── Prompt templates ──────────────────────────────────────────────────────────

HYDE_SYSTEM_PROMPT = """You are a helpful assistant that writes short, 
factual-sounding passages to help with document retrieval.
Your response must be a single paragraph of 3-5 sentences.
Write as if you are stating facts from a reference document.
Do not start with "I" or explain what you're doing.
Do not ask questions. Just write the passage."""

HYDE_USER_TEMPLATE = """Write a short passage that directly answers this question:

Question: {query}

Write a concise, factual passage (3-5 sentences) that would appear in a 
document answering this question. Focus on key concepts and terminology."""


# ── HyDE Expander ─────────────────────────────────────────────────────────────

class HyDEExpander:
    """
    Generates a hypothetical document for a query and embeds it.

    The hypothetical document is generated by the LLM at low temperature
    (0.1) to keep it focused and factual-sounding. We use a small
    max_tokens limit (250) because we only need enough text to produce
    a good embedding — we don't need a full essay.

    Usage:
        expander = HyDEExpander()

        # Get hypothetical answer text + its embedding vector
        hypo_text, hypo_vector = expander.expand("What is attention?")

        # Then pass hypo_vector to HybridSearcher.search_by_vector()
    """

    def __init__(self):
        cfg = get_settings()

        # Low temperature = more focused, deterministic hypothetical answer
        # We want something factual-sounding, not creative
        self.llm = ChatGroq(
            api_key=cfg.groq_api_key,
            model_name=cfg.groq_model_name,
            temperature=0.1,
            max_tokens=250,          # short answer is enough for embedding
        )

        self._cache: dict = {}       # simple in-memory cache by query string

    def expand(
        self,
        query: str,
        use_cache: bool = True,
    ) -> Tuple[str, np.ndarray]:
        """
        Generate a hypothetical answer and embed it.

        Args:
            query     : the user's raw question
            use_cache : if True, same query returns cached result
                        avoids redundant LLM calls for repeated queries

        Returns:
            Tuple of:
              hypothetical_text : the generated passage (string)
              hyde_vector       : embedding of that passage, shape (1, 384)

        Raises:
            RuntimeError if the LLM call fails (network, rate limit, etc.)
        """
        # ── Cache check ───────────────────────────────────────────────────────
        if use_cache and query in self._cache:
            print("[HyDE] Cache hit — reusing previous expansion")
            return self._cache[query]

        # ── Generate hypothetical answer ──────────────────────────────────────
        print(f"[HyDE] Generating hypothetical answer for: '{query[:60]}...'")

        messages = [
            SystemMessage(content=HYDE_SYSTEM_PROMPT),
            HumanMessage(content=HYDE_USER_TEMPLATE.format(query=query)),
        ]

        try:
            response = self.llm.invoke(messages)
            hypothetical_text = response.content.strip()
        except Exception as e:
            raise RuntimeError(f"HyDE LLM call failed: {e}") from e

        print(f"[HyDE] Hypothetical answer ({len(hypothetical_text.split())} words):")
        print(f"       {hypothetical_text[:120]}...")

        # ── Embed the hypothetical answer ─────────────────────────────────────
        # This vector is answer-shaped → closer to document chunks than
        # the question embedding would be
        hyde_vector = embed_query(hypothetical_text)
        # shape: (1, 384), float32, L2-normalized

        result = (hypothetical_text, hyde_vector)

        # ── Cache and return ──────────────────────────────────────────────────
        if use_cache:
            self._cache[query] = result

        return result

    def expand_with_fallback(
        self,
        query: str,
        use_cache: bool = True,
    ) -> Tuple[str, np.ndarray]:
        """
        Like expand(), but falls back to raw query embedding if LLM fails.

        This is what the RAG chain uses — if Groq is down or rate-limited,
        we gracefully degrade to standard embedding search rather than
        crashing the entire query.

        Returns the same (text, vector) tuple:
          - On success: hypothetical text + its embedding
          - On failure: original query + its embedding
        """
        try:
            return self.expand(query, use_cache=use_cache)
        except Exception as e:
            print(f"[HyDE] ⚠ LLM call failed, falling back to raw query: {e}")
            raw_vector = embed_query(query)
            return query, raw_vector

    def clear_cache(self) -> None:
        """Clear the in-memory cache (useful between test runs)."""
        self._cache.clear()


# ── Module-level singleton ─────────────────────────────────────────────────────

_hyde_expander: Optional[HyDEExpander] = None


def get_hyde_expander() -> HyDEExpander:
    """
    Returns the global HyDEExpander instance, creating it on first call.
    The LLM client is initialized once and reused — avoids overhead of
    recreating the client on every query.
    """
    global _hyde_expander
    if _hyde_expander is None:
        _hyde_expander = HyDEExpander()
    return _hyde_expander
